/* Generated By:JavaCC: Do not edit this line. TPTP.java */
import java.util.*;
import java.util.HashSet;

class Robot {
    public long X;
    public long Y;

    public Robot(){
        this.X = 0;
        this.Y = 0;
    }
}
class StepReference{
    public String stepName;
    public int lineNumber;

    public StepReference(String name, int line){
        this.stepName=name;
        this.lineNumber=line;
    }
}
class ConditionInfo{
    public String identifier;  // which parameter (ID1 or ID2)
    public int threshold;       // the NUM value

    public ConditionInfo(String id, int thresh) {
        this.identifier = id;
        this.threshold = thresh;
    }
}
class ArithExpression {
    public int numSum; // sum of all individuals non variable integers
    public int id1Count; // additive occurences of id1
    public int id2Count; // additive occurences of id2


    public ArithExpression(){
        this.numSum = 0;
        this.id1Count = 0;
        this.id2Count = 0;
    }

    //eval the value of this arithExpression with givens values of ID1,ID2
    public int eval(int ID1, int ID2){
        return numSum + (ID1 * id1Count) + (ID2 * id2Count);
    }

    //merge another ArithExpression with this one
    public void merge(ArithExpression other){
        this.numSum += other.numSum;
        this.id1Count += other.id1Count;
        this.id2Count += other.id2Count;
    }
    //S3 checker, for when x<d is false
    // expr is smallest at x=d as x>=d. Set other ID to 0 and check non-neg
    public boolean checkS3(boolean condUsesID1, int condThreshold){
        int result, ID1, ID2;

        if(condUsesID1){
            ID1 = condThreshold;
            ID2 = 0;
        }else{
            ID1 = 0;
            ID2 = condThreshold;
        }

        result = eval(ID1, ID2);
        return (result >= 0);
    }
}

public class TPTP implements TPTPConstants {
    private Set<String> stepNames=new HashSet<String>(); //store step names
    private Set<String> parameterNames=new HashSet<String>();
    private String runStepName = null;
    private Map<String, StepReference> stepReferences = new HashMap<String,StepReference >(); //maps step names to their reference

    private static boolean nonSimple = false;
    private static int lastNumeral = 0;
    private static String currentID1 = null;
    private static String currentID2 = null;
    private static String firstNonSimpleStep=null;
    private static String currentStepName=null;

    private static String decodeMessage(ParseException e) {
        if (e.currentToken == null) return e.getMessage();

        Token current = e.currentToken;
        Token next = current.next;
        if (next == null) return e.getMessage();

        String encountered = next.image;
        if (encountered == null) encountered = "";
        String currentImg = current.image;
        if (currentImg == null) currentImg = "";

        if (next.kind == 0) {
            return "Unexpected end of file.";
        }

        // Determine what token types were expected
        boolean expectsEOF = false;
        boolean expectsLT = false;

        if (e.expectedTokenSequences != null && tokenImage != null) {
            for (int[] seq : e.expectedTokenSequences) {
                for (int kind : seq) {
                    if (kind >= 0 && kind < tokenImage.length) {
                        String img = tokenImage[kind];
                        if ("\"<\"".equals(img)) expectsLT = true;
                        if ("<EOF>".equals(img)) expectsEOF = true;
                    }
                }
            }
        }

        // Specific tailored messages based on typical TPTP violations
        if (expectsEOF && ";".equals(encountered)) {
            return "Unexpected semicolon after the run instruction.";
        }

        if (expectsLT && ("+".equals(encountered) || "-".equals(encountered) || "*".equals(encountered))) {
            return "Condition is not of the form ID<NUM; encountered arithmetic operation.";
        }

        if ("if".equals(currentImg) && "(".equals(encountered)) {
            return "Syntax error: expected an identifier after \"if\"; got \"(\".";
        }

        if (";".equals(encountered)) {
             return "Unexpected semicolon.";
        }

        // Generic fallback combining the expected tokens cleanly
        StringBuilder expectedStr = new StringBuilder();
        if (e.expectedTokenSequences != null && tokenImage != null) {
            for (int i = 0; i < e.expectedTokenSequences.length; i++) {
                for (int j = 0; j < e.expectedTokenSequences[i].length; j++) {
                    int kind = e.expectedTokenSequences[i][j];
                    if (kind >= 0 && kind < tokenImage.length) {
                        String exp = tokenImage[kind];
                        if (exp.startsWith("\"") && exp.endsWith("\"")) {
                            exp = exp.substring(1, exp.length() - 1);
                        }
                        if (expectedStr.indexOf(exp) == -1) {
                            expectedStr.append(exp).append(" ");
                        }
                    }
                }
            }
        }

        String exp = expectedStr.toString().trim().replace(" ", ", ");
        if (exp.isEmpty()) {
            return "custom Syntax error: unexpected token '" + encountered + "'.";
        }
        return "custom Syntax error: unexpected token '" + encountered + "'. Expected one of: " + exp + ".";
    }

    public static void main( String[] args ) throws ParseException {
        TPTP parser = new TPTP( System.in ) ;
        try{
            parser.Program();
            System.out.println("Success");
            if(nonSimple){
                System.out.println("Non-simple");
                System.out.println(firstNonSimpleStep);
            }else{
                System.out.println("Simple");
            }
        }
        catch(ParseException e){
            System.out.println("HERE WE ARE");

            if (e.currentToken == null) {
                 System.out.println("ALSO HERE");
                // A custom ParseException where we prefix line number inside the message
                String msg = e.getMessage();
                if (msg != null && msg.contains("|")) {
                     System.out.println("perchance");
                    int pipeIdx = msg.indexOf('|');
                    String lineStr = msg.substring(0, pipeIdx);
                    System.err.println(lineStr);
                    System.err.println(msg.substring(pipeIdx + 1));
                } else {
                    System.out.println("Indubitably");
                    System.err.println("1");
                    System.err.println(msg != null ? msg : "Unknown syntax error");
                }
            } else {
                System.out.println("NAH WE ARE HERE");
                // An auto-generated JavaCC parse error - make our own
                Token errorToken = e.currentToken.next;
                if (errorToken != null) {
                    System.err.println(errorToken.beginLine);
                } else {
                    System.err.println("1");
                }
                System.err.println("custom"+decodeMessage(e));
            }
        }
            // System.out.println("Failure");
            // Token errorToken = e.currentToken.next;//Get token where error
            // if(errorToken !=null){
            //     System.err.println(errorToken.beginLine); 
            // }else{
            //     System.err.println("1");
            // }
            // String msg=e.getMessage();
            // // if (msg.contains("Was expecting") && msg.contains("<")) {
            // //     msg = "Condition must be in the form ID<NUM; found arithmetic or invalid expression.";
            // // }
            // // else if (msg.contains("Encountered")){
            // //     msg = "Syntax error: unexpected token '" + errorToken.image + "'.";
            // // }

            // if(msg==null || msg.isEmpty()){
            //     msg="Unexpected token: "+ (errorToken != null? errorToken.image: "unknown");
            // } else{
            //     decodeMessage(msg)
            // }
            // System.err.println(msg);

        catch(TokenMgrError e){
            System.out.println("Failure");
            String msg = e.getMessage();
            int lineIndex = msg.indexOf("line ");
            int commaIndex = msg.indexOf(",", lineIndex);
            int lineNum = 1;
            try {
                int lineIdx = msg.indexOf("line ");
                if (lineIdx != -1) {
                    int commaIdx = msg.indexOf(",", lineIdx);
                    if (commaIdx != -1) {
                        lineNum = Integer.parseInt(msg.substring(lineIdx + 5, commaIdx).trim());
                    }
                }
            } catch (Exception ex) {
                lineNum = 1;
            }
            System.err.println(lineNum);
            System.err.println("Lexical error: " + msg);

            // if (lineIndex != -1 && commaIndex != -1) {
            //     String lineNumber = msg.substring(lineIndex + 5, commaIndex);
            //     System.err.println(lineNumber);
            // } else {
            //     System.err.println("Unknown line");
            // }

        }
        catch (Exception e){
            System.out.println("Failure");
            System.err.println("1");
            System.err.println("Internal error"+e.getMessage());
        }
    }
    private static void markNonSimple(){
        if(!nonSimple && currentStepName!=null){
            firstNonSimpleStep=currentStepName; //records first step that caused to not be simple
            nonSimple = true;
        }

    }

  final public void Program() throws ParseException {
    label_1:
    while (true) {
      Step();
      jj_consume_token(SEMICOLON);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case IDENTIFIER:
        ;
        break;
      default:
        jj_la1[0] = jj_gen;
        break label_1;
      }
    }
    Run();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 0:
      jj_consume_token(0);
      break;
    case UNEXPECTED:
      jj_consume_token(UNEXPECTED);
        {if (true) throw new ParseException("Unexpected character: '" + token.image + "'");}
      break;
    default:
      jj_la1[1] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
        //cond 10 - step name in run must be present
        if(!stepNames.contains(runStepName)){
            {if (true) throw new ParseException(token.beginLine+"|Step '" + runStepName + "' mentioned in run instruction does not exist.");}
        }
  }

  final public void pairID() throws ParseException {
    Token id1Tok;
    Token id2Tok;
    String id1;
    String id2;
    jj_consume_token(LPAREN);
    id1Tok = jj_consume_token(IDENTIFIER);
    jj_consume_token(COMMA);
    id2Tok = jj_consume_token(IDENTIFIER);
    jj_consume_token(RPAREN);
        id1=id1Tok.image;
        id2=id2Tok.image;
        // recordParameterPair(token.beginLine, id1, id2);

  }

  final public void Step() throws ParseException {
    Token name;
    Token id1, id2;
    Token nextStep, elseStep;
    ConditionInfo cond;
    ArithExpression e1=null, e2=null, e3=null, e4=null;
    boolean isSimple;
    name = jj_consume_token(IDENTIFIER);
        //Cond 8
        if(stepNames.contains(name.image)){
            {if (true) throw new ParseException(name.beginLine+"|Duplicate step name: " + name.image);}
        }
        //Cond 5: step name cannot be same as earlier param name // does not fully work
        if(parameterNames.contains(name.image)){
            {if (true) throw new ParseException(name.beginLine+"|Cannot have Step name '"+name.image+"' as already referenced as a parameter name");}
        }
        stepNames.add(name.image);
        currentStepName=name.image;
    jj_consume_token(COLON);
    jj_consume_token(IF);
    cond = Cond();
    jj_consume_token(LPAREN);
    id1 = jj_consume_token(IDENTIFIER);
    jj_consume_token(COMMA);
    id2 = jj_consume_token(IDENTIFIER);
    jj_consume_token(RPAREN);
        currentID1 = id1.image;
        currentID2 = id2.image;
        if (!cond.identifier.equals(id1.image) && !cond.identifier.equals(id2.image)) {
            {if (true) throw new ParseException(id1.beginLine+"|Condition uses parameter: "+cond.identifier+" but must use parameter " + id1.image + " or " + id2.image);}
        }
        if(stepNames.contains(id1.image)){
            {if (true) throw new ParseException(id1.beginLine+"|Parameter name '" + id1.image
            + "' conflicts with step name.");}
        }
        if (stepNames.contains(id2.image)) {
            {if (true) throw new ParseException(id2.beginLine+"|Parameter name '" + id2.image
                + "' conflicts with step name.");}
        }
         // Further Condition 6: id1 and id2 must be different
        if (id1.image.equals(id2.image)) {
            {if (true) throw new ParseException(id2.beginLine+"|Parameter names must be different in step: " + name);}
        }

        parameterNames.add(id1.image);
        parameterNames.add(id2.image);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case BECOMES:
      jj_consume_token(BECOMES);
      jj_consume_token(LPAREN);
      e1 = Expr(false);
      jj_consume_token(COMMA);
      e2 = Expr(false);
      jj_consume_token(RPAREN);
      jj_consume_token(AND);
      break;
    default:
      jj_la1[2] = jj_gen;
      ;
    }
    nextStep = jj_consume_token(IDENTIFIER);
        stepReferences.put(nextStep.image, new StepReference(nextStep.image, nextStep.beginLine));
    jj_consume_token(ELSE);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case LPAREN:
      jj_consume_token(LPAREN);
      e3 = Expr(true);
      jj_consume_token(COMMA);
      e4 = Expr(true);
      jj_consume_token(RPAREN);
      jj_consume_token(AND);
      break;
    default:
      jj_la1[3] = jj_gen;
      ;
    }
    elseStep = jj_consume_token(IDENTIFIER);
        stepReferences.put(elseStep.image, new StepReference(elseStep.image, elseStep.beginLine));
        //S3 check
        boolean condUsesID1=cond.identifier.equals(currentID1);
        if(e3!=null){
            if(!e3.checkS3(condUsesID1, cond.threshold)){
            markNonSimple();
            }
        }
        if(e4!=null){
            if(!e4.checkS3(condUsesID1, cond.threshold)){
            markNonSimple();
            }
        }
  }

  final public ConditionInfo Cond() throws ParseException {
    Token condIDTok;
    Token numTok;
    condIDTok = jj_consume_token(IDENTIFIER);
    jj_consume_token(LT);
    numTok = jj_consume_token(NUMERAL);
        int num=Integer.parseInt(numTok.image);
        {if (true) return new ConditionInfo(condIDTok.image,num);}
    throw new Error("Missing return statement in function");
  }

  final public void Run() throws ParseException {
    Token StepName;
    Token n1Token,n2Token;
    jj_consume_token(RUN);
    StepName = jj_consume_token(IDENTIFIER);
    jj_consume_token(LPAREN);
    n1Token = jj_consume_token(NUMERAL);
    jj_consume_token(COMMA);
    n2Token = jj_consume_token(NUMERAL);
    jj_consume_token(RPAREN);
        runStepName = StepName.image;
  }

  final public ArithExpression Expr(boolean allowsNegatives) throws ParseException {
    ArithExpression exp = new ArithExpression();
    boolean termWasNumeral;
    Term(allowsNegatives,exp);
    label_2:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case PLUS:
      case MINUS:
        ;
        break;
      default:
        jj_la1[4] = jj_gen;
        break label_2;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case PLUS:
        jj_consume_token(PLUS);
        Term(allowsNegatives,exp);
        break;
      case MINUS:
        jj_consume_token(MINUS);
        termWasNumeral = Term(allowsNegatives, exp);
        //Rule s2 E1/E2 cannot have subtraction
        if (!allowsNegatives){
            markNonSimple();
        }
        //Rule p:
        if(!termWasNumeral){
            markNonSimple();
        } else{
            exp.numSum -= (2*lastNumeral); //double negate as added prevbiously
        }
        break;
      default:
        jj_la1[5] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
        {if (true) return exp;}
    throw new Error("Missing return statement in function");
  }

  final public boolean Term(boolean allowsNegatives, ArithExpression exp) throws ParseException {
    boolean factorWasNumeral;
    factorWasNumeral = Factor(allowsNegatives,exp);
    label_3:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case MULT:
        ;
        break;
      default:
        jj_la1[6] = jj_gen;
        break label_3;
      }
      jj_consume_token(MULT);
      Factor(allowsNegatives, exp);
            //multiplication makes expression non positive
            markNonSimple();
    }
        {if (true) return factorWasNumeral;}
    throw new Error("Missing return statement in function");
  }

  final public boolean Factor(boolean allowsNegatives, ArithExpression exp) throws ParseException {
    Token numeralToken;
    Token idToken;
    int numeral;
    boolean isNumeral=false;
    boolean factorWasNumeral;
    ArithExpression nestedExp;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case NUMERAL:
      numeralToken = jj_consume_token(NUMERAL);
            isNumeral=true;
            numeral=Integer.parseInt(numeralToken.image);
            lastNumeral=numeral;
            exp.numSum +=numeral;
      break;
    case IDENTIFIER:
      idToken = jj_consume_token(IDENTIFIER);
            //must be ID1 or ID2
            if(idToken.image.equals(currentID1)){
                exp.id1Count++;
            } else if (idToken.image.equals(currentID2)){
                exp.id2Count++;
            } else{
                {if (true) throw new ParseException(idToken.beginLine+"|Identifier '" + idToken.image + "' is not a parameter in this step.");}
            }
      break;
    case LPAREN:
      jj_consume_token(LPAREN);
      nestedExp = Expr(allowsNegatives);
      jj_consume_token(RPAREN);
            exp.merge(nestedExp);
      break;
    default:
      jj_la1[7] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
        {if (true) return isNumeral;}
    throw new Error("Missing return statement in function");
  }

  /** Generated Token Manager. */
  public TPTPTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private int jj_gen;
  final private int[] jj_la1 = new int[8];
  static private int[] jj_la1_0;
  static {
      jj_la1_init_0();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0x80000,0x200001,0x40,0x1000,0x18000,0x18000,0x20000,0xc1000,};
   }

  /** Constructor with InputStream. */
  public TPTP(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public TPTP(java.io.InputStream stream, String encoding) {
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new TPTPTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 8; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 8; i++) jj_la1[i] = -1;
  }

  /** Constructor. */
  public TPTP(java.io.Reader stream) {
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new TPTPTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 8; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 8; i++) jj_la1[i] = -1;
  }

  /** Constructor with generated Token Manager. */
  public TPTP(TPTPTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 8; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(TPTPTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 8; i++) jj_la1[i] = -1;
  }

  private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }


/** Get the next Token. */
  final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  private java.util.List jj_expentries = new java.util.ArrayList();
  private int[] jj_expentry;
  private int jj_kind = -1;

  /** Generate ParseException. */
  public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[22];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 8; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 22; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = (int[])jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

}
