/* TPTP.java */
/* Generated By:JavaCC: Do not edit this line. TPTP.java */
import java.util.*;
// class Expression{
//     //types are of N-number, V-variable, + , - , *
//     char type;
//     long val; //for type N
//     String varName, // for V
//     Expression left,right; //used in operators 
//     Expression(long v) { this.type = 'N'; this.val = v; }//Number constructor

//     Expression(String name) { this.type = 'V'; this.varName = name; } // var constructor

//     Expression(char op, Expression l, Expression r) { // op constructor
//         this.type = op; this.left = l; this.right = r;
//     }
// }
// class Step{

// }
public class TPTP implements TPTPConstants {
    private Set<String> stepNames=new HashSet<String>(); //store step names
    private String runStepName = null;
    public static void main( String[] args ) throws ParseException {
        TPTP parser = new TPTP( System.in ) ;
        try{
            parser.Program();
            System.out.println("Success");
        }
        catch(ParseException e){
            System.out.println("Failure");
            System.err.println(e.currentToken.next.beginLine);
            System.err.println("Syntax Error: " + e.getMessage());
        }
        catch(TokenMgrError e){
            System.out.println("Failure");
            String msg = e.getMessage();
            int lineIndex = msg.indexOf("line ");
            int commaIndex = msg.indexOf(",", lineIndex);

            if (lineIndex != -1 && commaIndex != -1) {
                String lineNumber = msg.substring(lineIndex + 5, commaIndex);
                System.err.println(lineNumber);
            } else {
                System.err.println("Unknown line");
            }
        }
        catch (Exception e){
            System.out.println("Failure");
            System.err.println("0");
            System.err.println(e.getMessage());
        }
    }

  final public void Program() throws ParseException {
    label_1:
    while (true) {
      Step();
      jj_consume_token(SEMICOLON);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case IDENTIFIER:{
        ;
        break;
        }
      default:
        jj_la1[0] = jj_gen;
        break label_1;
      }
    }
    Run();
    jj_consume_token(0);
if(!stepNames.contains(runStepName)){
            {if (true) throw new ParseException("Step '" + runStepName + "' mentioned in run instruction does not exist.");}
        }
}

  final public void Step() throws ParseException {Token name;
    Token id1, id2;
    Token nextStep, elseStep;
    String cond;
    String e1=null, e2=null, e3=null, e4=null;
    boolean isSimple;
    name = jj_consume_token(IDENTIFIER);
    jj_consume_token(COLON);
    jj_consume_token(IF);
    cond = Cond();
    jj_consume_token(LPAREN);
    id1 = jj_consume_token(IDENTIFIER);
    jj_consume_token(COMMA);
    id2 = jj_consume_token(IDENTIFIER);
    jj_consume_token(RPAREN);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case BECOMES:{
      jj_consume_token(BECOMES);
      jj_consume_token(LPAREN);
      e1 = Expr();
      jj_consume_token(COMMA);
      e2 = Expr();
      jj_consume_token(RPAREN);
      jj_consume_token(AND);
      break;
      }
    default:
      jj_la1[1] = jj_gen;
      ;
    }
    nextStep = jj_consume_token(IDENTIFIER);
    jj_consume_token(ELSE);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case LPAREN:{
      jj_consume_token(LPAREN);
      e3 = Expr();
      jj_consume_token(COMMA);
      e4 = Expr();
      jj_consume_token(RPAREN);
      jj_consume_token(AND);
      break;
      }
    default:
      jj_la1[2] = jj_gen;
      ;
    }
    elseStep = jj_consume_token(IDENTIFIER);
//COnd 8
        if(stepNames.contains(name)){
            {if (true) throw new ParseException("Duplicate step name: " + name.image);}
        }
        stepNames.add(name.image);

        // Further Condition 6: id1 and id2 must be different
        if (id1.equals(id2)) {
            {if (true) throw new ParseException("Parameter names must be different in step: " + name);}
        }
}

  final public String Cond() throws ParseException {String condString="";
    //set tokens
    Token Id, Numeral;
    Id = jj_consume_token(IDENTIFIER);
    jj_consume_token(LT);
    Numeral = jj_consume_token(NUMERAL);
condString=Id.image.toString()+"<"+Numeral.image.toString();
        {if ("" != null) return(condString);}
    throw new Error("Missing return statement in function");
}

  final public void Run() throws ParseException {Token StepName;
    jj_consume_token(RUN);
    StepName = jj_consume_token(IDENTIFIER);
    jj_consume_token(LPAREN);
    jj_consume_token(NUMERAL);
    jj_consume_token(COMMA);
    jj_consume_token(NUMERAL);
    jj_consume_token(RPAREN);
runStepName = StepName.image;
}

  final public String Expr() throws ParseException {
    Term();
    label_2:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case PLUS:
      case MINUS:{
        ;
        break;
        }
      default:
        jj_la1[3] = jj_gen;
        break label_2;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case PLUS:{
        jj_consume_token(PLUS);
        break;
        }
      case MINUS:{
        jj_consume_token(MINUS);
        break;
        }
      default:
        jj_la1[4] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      Term();
    }
{if ("" != null) return("hello sally");}
    throw new Error("Missing return statement in function");
}

  final public void Term() throws ParseException {
    Factor();
    label_3:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case MULT:{
        ;
        break;
        }
      default:
        jj_la1[5] = jj_gen;
        break label_3;
      }
      jj_consume_token(MULT);
      Factor();
    }
}

  final public void Factor() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case NUMERAL:{
      jj_consume_token(NUMERAL);
      break;
      }
    case IDENTIFIER:{
      jj_consume_token(IDENTIFIER);
      break;
      }
    case LPAREN:{
      jj_consume_token(LPAREN);
      Expr();
      jj_consume_token(RPAREN);
      break;
      }
    default:
      jj_la1[6] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

  /** Generated Token Manager. */
  public TPTPTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private int jj_gen;
  final private int[] jj_la1 = new int[7];
  static private int[] jj_la1_0;
  static {
	   jj_la1_init_0();
	}
	private static void jj_la1_init_0() {
	   jj_la1_0 = new int[] {0x100000,0x80,0x2000,0x30000,0x30000,0x40000,0x182000,};
	}

  /** Constructor with InputStream. */
  public TPTP(java.io.InputStream stream) {
	  this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public TPTP(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source = new TPTPTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 7; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
	  ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 7; i++) jj_la1[i] = -1;
  }

  /** Constructor. */
  public TPTP(java.io.Reader stream) {
	 jj_input_stream = new SimpleCharStream(stream, 1, 1);
	 token_source = new TPTPTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 7; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
	if (jj_input_stream == null) {
	   jj_input_stream = new SimpleCharStream(stream, 1, 1);
	} else {
	   jj_input_stream.ReInit(stream, 1, 1);
	}
	if (token_source == null) {
 token_source = new TPTPTokenManager(jj_input_stream);
	}

	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 7; i++) jj_la1[i] = -1;
  }

  /** Constructor with generated Token Manager. */
  public TPTP(TPTPTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 7; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(TPTPTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 7; i++) jj_la1[i] = -1;
  }

  private Token jj_consume_token(int kind) throws ParseException {
	 Token oldToken;
	 if ((oldToken = token).next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 if (token.kind == kind) {
	   jj_gen++;
	   return token;
	 }
	 token = oldToken;
	 jj_kind = kind;
	 throw generateParseException();
  }


/** Get the next Token. */
  final public Token getNextToken() {
	 if (token.next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 jj_gen++;
	 return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
	 Token t = token;
	 for (int i = 0; i < index; i++) {
	   if (t.next != null) t = t.next;
	   else t = t.next = token_source.getNextToken();
	 }
	 return t;
  }

  private int jj_ntk_f() {
	 if ((jj_nt=token.next) == null)
	   return (jj_ntk = (token.next=token_source.getNextToken()).kind);
	 else
	   return (jj_ntk = jj_nt.kind);
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;

  /** Generate ParseException. */
  public ParseException generateParseException() {
	 jj_expentries.clear();
	 boolean[] la1tokens = new boolean[23];
	 if (jj_kind >= 0) {
	   la1tokens[jj_kind] = true;
	   jj_kind = -1;
	 }
	 for (int i = 0; i < 7; i++) {
	   if (jj_la1[i] == jj_gen) {
		 for (int j = 0; j < 32; j++) {
		   if ((jj_la1_0[i] & (1<<j)) != 0) {
			 la1tokens[j] = true;
		   }
		 }
	   }
	 }
	 for (int i = 0; i < 23; i++) {
	   if (la1tokens[i]) {
		 jj_expentry = new int[1];
		 jj_expentry[0] = i;
		 jj_expentries.add(jj_expentry);
	   }
	 }
	 int[][] exptokseq = new int[jj_expentries.size()][];
	 for (int i = 0; i < jj_expentries.size(); i++) {
	   exptokseq[i] = jj_expentries.get(i);
	 }
	 return new ParseException(token, exptokseq, tokenImage);
  }

  private boolean trace_enabled;

/** Trace enabled. */
  final public boolean trace_enabled() {
	 return trace_enabled;
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

}
