/* Generated By:JavaCC: Do not edit this line. TPTPConstants.java */

/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface TPTPConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int RUN = 4;
  /** RegularExpression Id. */
  int IF = 5;
  /** RegularExpression Id. */
  int BECOMES = 6;
  /** RegularExpression Id. */
  int ELSE = 7;
  /** RegularExpression Id. */
  int AND = 8;
  /** RegularExpression Id. */
  int COLON = 9;
  /** RegularExpression Id. */
  int COMMA = 10;
  /** RegularExpression Id. */
  int LT = 11;
  /** RegularExpression Id. */
  int LPAREN = 12;
  /** RegularExpression Id. */
  int RPAREN = 13;
  /** RegularExpression Id. */
  int SEMICOLON = 14;
  /** RegularExpression Id. */
  int PLUS = 15;
  /** RegularExpression Id. */
  int MINUS = 16;
  /** RegularExpression Id. */
  int MULT = 17;
  /** RegularExpression Id. */
  int NUMERAL = 18;
  /** RegularExpression Id. */
  int IDENTIFIER = 19;
  /** RegularExpression Id. */
  int LETTER = 20;
  /** RegularExpression Id. */
  int UNEXPECTED = 21;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"run\"",
    "\"if\"",
    "\"becomes\"",
    "\"else\"",
    "\"and\"",
    "\":\"",
    "\",\"",
    "\"<\"",
    "\"(\"",
    "\")\"",
    "\";\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "<NUMERAL>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<UNEXPECTED>",
  };

}
